// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_mnRsWgLg5bcURxOrfazekcmkhLf0DiE',
    appId: '1:1098765216246:web:91928f8e96f235c032bfd7',
    messagingSenderId: '1098765216246',
    projectId: 'resume-builder-b7065',
    authDomain: 'resume-builder-b7065.firebaseapp.com',
    storageBucket: 'resume-builder-b7065.firebasestorage.app',
    measurementId: 'G-2QNH1BSB9S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH264ef_mdhmOOnXVKrB3lYLlY_3xATvg',
    appId: '1:1098765216246:android:0aff022c12f5874532bfd7',
    messagingSenderId: '1098765216246',
    projectId: 'resume-builder-b7065',
    storageBucket: 'resume-builder-b7065.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsGaRVbj0uzXL9pedZhipy5-I_nB-wcek',
    appId: '1:1098765216246:ios:77b24898b28da2a532bfd7',
    messagingSenderId: '1098765216246',
    projectId: 'resume-builder-b7065',
    storageBucket: 'resume-builder-b7065.firebasestorage.app',
    androidClientId: '1098765216246-brc6l6q9tk8ipv8jmjg678ntr3af7398.apps.googleusercontent.com',
    iosClientId: '1098765216246-pe0324q8r0e8h18pfoccj85jpo5ivblk.apps.googleusercontent.com',
    iosBundleId: 'com.example.miniproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsGaRVbj0uzXL9pedZhipy5-I_nB-wcek',
    appId: '1:1098765216246:ios:77b24898b28da2a532bfd7',
    messagingSenderId: '1098765216246',
    projectId: 'resume-builder-b7065',
    storageBucket: 'resume-builder-b7065.firebasestorage.app',
    androidClientId: '1098765216246-brc6l6q9tk8ipv8jmjg678ntr3af7398.apps.googleusercontent.com',
    iosClientId: '1098765216246-pe0324q8r0e8h18pfoccj85jpo5ivblk.apps.googleusercontent.com',
    iosBundleId: 'com.example.miniproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_mnRsWgLg5bcURxOrfazekcmkhLf0DiE',
    appId: '1:1098765216246:web:1df0b3e2ee9d0d3132bfd7',
    messagingSenderId: '1098765216246',
    projectId: 'resume-builder-b7065',
    authDomain: 'resume-builder-b7065.firebaseapp.com',
    storageBucket: 'resume-builder-b7065.firebasestorage.app',
    measurementId: 'G-5WTZ5QEY4B',
  );
}
